import QRCode from "qrcode";
import toast from "react-hot-toast";
import { useEffect, useState } from "react";
import {
    useGenerateWrittenQrMutation,
    useGetWrittenQrStatusQuery,
    useFinalizeWrittenAnswerMutation,
} from "../../../../state/services/endpoints/written-answer";

interface WrittenAnswerCaptureProps {
    attemptId: string;
    questionId: string;
}

const WrittenAnswerCapture = ({ attemptId, questionId }: WrittenAnswerCaptureProps) => {
    const [generateQr, { isLoading: isGenerating }] = useGenerateWrittenQrMutation();
    const [finalizeAnswer, { isLoading: isFinalizing }] = useFinalizeWrittenAnswerMutation();
    const [qrDataUrl, setQrDataUrl] = useState<string | null>(null);
    const [tokenExpired, setTokenExpired] = useState(false);
    const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

    // The status row already exists (seeded at attempt-creation) whether or not a
    // QR has ever been generated, so this is always safe to poll from the start —
    // critically, it's what tells us NOT to auto-generate for an already-finalized answer.
    const { data: statusData } = useGetWrittenQrStatusQuery(
        { attemptId, questionId },
        { pollingInterval: 3000 },
    );

    const status = statusData?.data;

    const handleGenerate = async () => {
        try {
            const response = await generateQr({ attemptId, questionId }).unwrap();
            if (!response.data) return;
            setTokenExpired(false);
            const url = `${window.location.origin}/mobile/written-answer/${response.data.token}`;
            const dataUrl = await QRCode.toDataURL(url, { width: 240 });
            setQrDataUrl(dataUrl);
        } catch (error: any) {
            toast.error(error.data?.message || 'Failed to generate QR code');
        }
    };

    // Once we know the answer's current state, auto-generate a QR exactly once —
    // but only if it isn't already finalized (generating for a finalized answer is rejected).
    useEffect(() => {
        if (status && !status.isFinalized && !hasAutoGenerated) {
            setHasAutoGenerated(true);
            handleGenerate();
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [status, hasAutoGenerated]);

    // Re-check expiry client-side so the "Regenerate" prompt shows without waiting on a failed poll
    useEffect(() => {
        if (!status?.qrTokenExpiresAt) return;
        const remaining = new Date(status.qrTokenExpiresAt).getTime() - Date.now();
        if (remaining <= 0) {
            setTokenExpired(true);
            return;
        }
        const timeout = setTimeout(() => setTokenExpired(true), remaining);
        return () => clearTimeout(timeout);
    }, [status?.qrTokenExpiresAt]);

    const handleFinalize = async () => {
        try {
            await finalizeAnswer({ attemptId, questionId }).unwrap();
            toast.success('Written answer saved');
        } catch (error: any) {
            toast.error(error.data?.message || 'Failed to save written answer');
        }
    };

    if (status?.isFinalized) {
        return (
            <div className="rounded-md border border-green-200 bg-green-50 p-6 text-center space-y-1">
                <p className="text-green-700 font-medium">✓ Answer saved</p>
                <p className="text-sm text-green-600">{status.pageCount} page{status.pageCount === 1 ? '' : 's'} uploaded</p>
            </div>
        );
    }

    return (
        <div className="rounded-md border border-dashed border-borderLight p-6 text-center space-y-4">
            <p className="text-textPrimary font-medium">Scan this QR code with your phone to photograph and upload your written answer</p>

            {qrDataUrl && !tokenExpired && (
                <img src={qrDataUrl} alt="Scan to upload written answer" className="mx-auto rounded-md border border-borderLight" />
            )}

            {tokenExpired && (
                <p className="text-sm text-red-600">This QR code has expired.</p>
            )}

            {(tokenExpired || !qrDataUrl) && (
                <button
                    type="button"
                    onClick={handleGenerate}
                    disabled={isGenerating}
                    className="text-sm font-medium text-primary underline disabled:opacity-50"
                >
                    {isGenerating ? 'Generating...' : 'Generate QR Code'}
                </button>
            )}

            {!tokenExpired && qrDataUrl && (
                <button
                    type="button"
                    onClick={handleGenerate}
                    disabled={isGenerating}
                    className="text-sm text-textSecondary underline disabled:opacity-50 block mx-auto"
                >
                    Regenerate QR Code
                </button>
            )}

            <p className="text-sm text-textSecondary">
                {status ? `${status.pageCount} page${status.pageCount === 1 ? '' : 's'} uploaded` : 'No pages uploaded yet'}
                {status?.qrScannedAt && status.pageCount === 0 ? ' — QR scanned, waiting for upload...' : ''}
            </p>

            <button
                type="button"
                onClick={handleFinalize}
                disabled={!status || status.pageCount === 0 || isFinalizing}
                className="px-4 py-2 rounded-md bg-primary text-whiteColor text-sm font-medium disabled:opacity-50 disabled:cursor-not-allowed"
            >
                {isFinalizing ? 'Saving...' : 'Finish & Save Answer'}
            </button>
        </div>
    );
};

export default WrittenAnswerCapture;
